server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: ordersconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joshir/elastic-kafka-spring-config-repo.git
          username: joshir
          password: ${GITHUB_TOKEN}
          clone-on-start: true
    fail-fast: true